version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pharmacy_service
    environment:
      POSTGRES_DB: pharmacy
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: